" vim settings

set backspace=indent,eol,start
syntax enable
set relativenumber number
set smartindent
set tabstop=4 softtabstop=0 expandtab shiftwidth=4 smarttab
nnoremap <C-h> :silent set relativenumber! number!<CR>
autocmd FileType make set noexpandtab
autocmd BufWritePre * :%s/\s+$//e

" cursor

:autocmd InsertEnter * set cul 
:autocmd InsertLeave * set nocul

" plugins
" every time new plugin added, run: :PlugInstall

call plug#begin('~/.vim/plugged')

Plug 'dense-analysis/ale'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'SirVer/ultisnips'
Plug 'ervandew/supertab'
Plug 'ncm2/ncm2'
Plug 'roxma/nvim-yarp'
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-github'
Plug 'ncm2/ncm2-syntax'
Plug 'ncm2/ncm2-jedi'
Plug 'ncm2/ncm2-vim'

call plug#end()

" ale
let g:ale_linters = {
\    'python': ['flake8']
\}

" airline
let g:airline_theme = 'minimalist'

" ultisnips
let g:UltiSnipsUsePythonVersion = 3
let g:UltiSnipsExpandTrigger = '<C-j>'
let g:UltiSnipsJumpForwardTrigger = '<C-j>'
let g:UltiSnipsJumpBackwardTrigger = '<C-k>'

" " Track the engine.
Plug 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-z>"

" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"

" done.
