export PATH=$HOME/bin:$HOME/anaconda3/bin:/usr/local/opt/ruby/bin:$PATH

# iCloud alias if on mac
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias ic='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs'
fi

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="customcolors"

# zplug
export ZPLUG_HOME=$HOME/zplug

if [[ ! -e $ZPLUG_HOME/init.zsh ]]; then
    # install zplug if missing 
    git clone https://github.com/zplug/zplug.git "$ZPLUG_HOME"
fi

source $ZPLUG_HOME/init.zsh

# let zplug update itself
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# zsh async plugin
# zplug "mafredri/zsh-async", from:"github", use:"async.zsh"

# zsh autosuggestions
zplug "zsh-users/zsh-autosuggestions"

# fish-style syntax highlighting
#
# this must be loaded after compinit, so use defer.
zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug check || zplug install
zplug load

# aliases
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gl='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'
alias ll="ls -AlFGgh"

plugins=(
    git
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# export PATH="/usr/local/opt/ruby/bin:$PATH"
eval "$(rbenv init -)"
