export PATH=$HOME/bin:$HOME/anaconda3/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/sempervirens/.oh-my-zsh"
alias ic='cd ~/Library/Mobile\ Documents/com~apple~CloudDocs'

ZSH_THEME="customcolors"

# aliases
alias gs="git status"
alias gc="git commit"
alias ga="git add"
alias gl='git log --pretty=format:"%h%x09%an%x09%ad%x09%s"'
alias ll="ls -AlFGgh"

plugins=(
    git
    zsh-syntax-highlighting
    zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

export PATH="/usr/local/opt/ruby/bin:$PATH"
eval "$(rbenv init -)"
